include: package:lints/recommended.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    todo: ignore

linter:
  rules:
    avoid_unnecessary_containers: true
    no_logic_in_create_state: true
    non_constant_identifier_names: false
    unnecessary_string_escapes: false
    annotate_overrides: false
    constant_identifier_names: false